module.exports = {
  apps: [
    {
      name: 'blog-cron-pages-9am',
      cwd: __dirname,
      script: 'pnpm',
      args: 'cron:pages',
      interpreter: 'none',
      autorestart: false,
      cron_restart: '0 9 * * *',
      time: true,
      env_file: '.env',
      env: { TZ: 'Asia/Seoul' },
    },
    {
      name: 'blog-cron-exclude-9am',
      cwd: __dirname,
      script: 'pnpm',
      args: 'cron:exclude',
      interpreter: 'none',
      autorestart: false,
      cron_restart: '0 9 * * *',
      time: true,
      env_file: '.env',
      env: { TZ: 'Asia/Seoul' },
    },
    {
      name: 'blog-cron-dogmaru-9am',
      cwd: __dirname,
      script: 'pnpm',
      args: 'cron:dogmaru',
      interpreter: 'none',
      autorestart: false,
      cron_restart: '0 9 * * *',
      time: true,
      env_file: '.env',
      env: { TZ: 'Asia/Seoul' },
    },
    {
      name: 'blog-cron-root-9am',
      cwd: __dirname,
      script: 'pnpm',
      args: 'cron:root',
      interpreter: 'none',
      autorestart: false,
      cron_restart: '0 9 * * *',
      time: true,
      env_file: '.env',
      env: { TZ: 'Asia/Seoul' },
    },
  ],
};
