module.exports = {
  apps: [
    {
      name: 'blog-cron-bot-keywords',
      cwd: __dirname,
      script: 'dist/pm2-scheduler.js',
      instances: 1,
      exec_mode: 'fork',
      env_file: '.env',
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '512M',
    },
    {
      name: 'blog-cron-bot-root',
      cwd: __dirname,
      script: 'dist/pm2-scheduler-root.js',
      instances: 1,
      exec_mode: 'fork',
      env_file: '.env',
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '512M',
    },
    {
      name: 'blog-cron-bot-all-sheets',
      cwd: __dirname,
      script: 'dist/pm2-scheduler-all-sheets.js',
      instances: 1,
      exec_mode: 'fork',
      env_file: '.env',
      env: {
        WORKFLOW_RUN_TIMES: '08:00',
      },
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '512M',
    },
    {
      // requires `pnpm --dir dashboard build` beforehand (produces dashboard/.next)
      name: 'blog-cron-dashboard',
      cwd: `${__dirname}/dashboard`,
      script: 'pnpm',
      args: 'start -- -p 4500',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      env_file: '.env.local',
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '512M',
    },
  ],
};
